from timepiece.tests.crmcontent import *
from timepiece.tests.management import *
from timepiece.tests.projects import *
from timepiece.tests.project_list import *
from timepiece.tests.relationships import *
from timepiece.tests.schedule import *
from timepiece.tests.search import *
from timepiece.tests.tracking import *
from timepiece.tests.user_settings import *
from timepiece.tests.utils import *
from timepiece.tests.template_tags import *
