# Generated by Django 5.1 on 2024-08-30 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0003_auto_20151119_0906"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="point_person",
            field=models.ForeignKey(
                limit_choices_to={"is_staff": True},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.ForeignKey(
                limit_choices_to={"type": "project-status"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects_with_status",
                to="crm.attribute",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.ForeignKey(
                limit_choices_to={"type": "project-type"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects_with_type",
                to="crm.attribute",
            ),
        ),
    ]
